---
apiVersion: v1
kind: Namespace
metadata:
  name: kubebuilder-demo
---
apiVersion: apps.kubebuilder.demo/v1alpha1
kind: WebApp
metadata:
  name: webapp-sample
  namespace: kubebuilder-demo
spec:
  replicas: 2
  image: nginx:latest
  port: 80
