---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp-sample
---
apiVersion: apps.kubebuilder.demo/v1alpha1
kind: WebApp
metadata:
  name: webapp-sample
  namespace: webapp-sample
spec:
  replicas: 3
  image: nginx:latest
  port: 8080