---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp-operator
---
apiVersion: apps.kubebuilder.demo/v1alpha1
kind: WebApp
metadata:
  name: webapp-sample
  namespace: webapp-operator
spec:
  replicas: 2
  image: nginx:latest
  port: 80